---
- hosts: endpoints
  become: true
  tasks:
  - name: Ensure docker service is running
    systemd:
      name: docker
      state: started

  - name: Add edge user to docker group
    user:
      name: "{{ username }}"
      groups: "docker, systemd-journal"

  handlers:
    - name: docker status
      service: name=docker state=started
