---
- hosts: endpoints
  become: true
  tasks:
  - name: Ensure docker service is running
    systemd:
      name: docker
      state: started

  - name: Add edge user to docker group
    user:
      name: "{{ username }}"
      groups: "docker, systemd-journal"
    
  - name: Allow HTTP pulling from private docker registry
    shell: echo '{ "insecure-registries":["{{ registry_ip }}"] }' > /etc/docker/daemon.json

  - name: Restart docker service
    command: systemctl restart docker

  - name: Reload ip settings
    command: sysctl -p

  - name: Run Netserver
    command: netserver

  handlers:
    - name: docker status
      service: name=docker state=started
