---
- hosts: clouds
  become: true
  tasks:
  - name: Create cloud controller image
    shell: |
      if [ "{{ cloud_controller }}" -gt "0" ]; then
        cp /var/lib/libvirt/images/base.qcow2 /var/lib/libvirt/images/cloud_controller.qcow2
      fi

  - name: Create cloud images
    shell: |
      for i in $(seq "{{ cloud_start }}" "{{ cloud_end }}"); do
        cp /var/lib/libvirt/images/base.qcow2 /var/lib/libvirt/images/cloud${i}.qcow2
      done

  - name: Add cloudinit disk for cloud controller
    shell: |
      if [ "{{ cloud_controller }}" -gt "0" ]; then
        cloud-localds -N "/home/{{ username }}/.edge/network_config_cloud_controller.yml" /var/lib/libvirt/images/user_data_cloud_controller.img "/home/{{ username }}/.edge/user_data_cloud_controller.yml"
      fi

  - name: Add cloudinit disk for cloud
    shell: |
      for i in $(seq "{{ cloud_start }}" "{{ cloud_end }}"); do
        cloud-localds -N "/home/{{ username }}/.edge/network_config_cloud${i}.yml" /var/lib/libvirt/images/user_data_cloud${i}.img "/home/{{ username }}/.edge/user_data_cloud${i}.yml"
      done
