---
- hosts: endpoints
  become: true
  tasks:
  - name: Create endpoint images
    shell: |
      for i in $(seq "{{ endpoint_start }}" "{{ endpoint_end }}"); do
        cp /var/lib/libvirt/images/base.qcow2 /var/lib/libvirt/images/endpoint${i}.qcow2
      done

  - name: Add cloudinit disk
    shell: |
      for i in $(seq "{{ endpoint_start }}" "{{ endpoint_end }}"); do
        cloud-localds -N "/home/{{ username }}/.edge/network_config_endpoint${i}.yml" /var/lib/libvirt/images/user_data_endpoint${i}.img "/home/{{ username }}/.edge/user_data_endpoint${i}.yml"
      done
