---
- hosts: cloudcontroller
  become: true
  tasks:
  - name: Create job file
    shell: |
      cat > "/home/{{ username }}/job-template.yaml" <<EOF
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: {{ app_name }}-%ITEM
      spec:
        template:
          metadata:
            name: {{ app_name }}
          spec:
            containers:
            - name: {{ app_name }}
              image: {{ image }}
              imagePullPolicy: Always
              resources:
                requests:
                  memory: "{{ memory_req }}Gi"
                  cpu: {{ cpu_req }}
              env:
              - name: SLEEP_TIME
                value: "{{ sleep_time }}"
            restartPolicy: Never
      EOF

  - name: Create job directory
    file:
      path: "/home/{{ username }}/jobs"
      state: directory
  
  - name: Create job multiple times
    shell: |
      for i in `seq 0 {{ replicas }}`
      do
        cat "/home/{{ username }}/job-template.yaml" | sed "s/\%ITEM/$i/" > "/home/{{ username }}/jobs/job-$i.yaml"
      done

  - name: Launch jobs
    command: kubectl create --kubeconfig="/home/{{ username }}/.kube/config" -f "/home/{{ username }}/jobs"
