---
- hosts: cloudcontroller
  become: true
  tasks:
    - name: Configure node ip
      lineinfile:
        path: /etc/default/kubelet
        line: KUBELET_EXTRA_ARGS=--node-ip={{ cloud_ip }}
        create: true

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: true
        state: restarted

    - name: Forward IPv4 and let iptables see bridged traffic
      shell: |
        cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
        overlay
        br_netfilter
        EOF

        sudo modprobe overlay
        sudo modprobe br_netfilter

        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-iptables  = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward                 = 1
        EOF

        sudo sysctl --system

    - name: Initialize the Kubernetes cluster using kubeadm
      command: >
        kubeadm init
          --apiserver-advertise-address={{ cloud_ip }}
          --apiserver-cert-extra-sans={{ cloud_ip }}
          --node-name {{ ansible_hostname }}
          --pod-network-cidr=10.244.0.0/16
          --kubernetes-version=1.25.3
          --image-repository={{ registry_ip }}

    - name: Create user Kubernetes directory
      file:
        path: /home/{{ username }}/.kube
        state: directory

    - name: Copy Kubernetes files to user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ username }}/.kube/config
        owner: "{{ username }}"
        group: "{{ username }}"
        remote_src: true

    - name: Enable networking with Calico, only for cloud mode
      shell: |
        if [ "{{ cloud_mode }}" -gt "0" ]; then
          kubectl create --kubeconfig="/home/{{ username }}/.kube/config" -f /kube-flannel.yml
        fi

    - name: Create join command for worker nodes (cloud-only)
      shell: |
        echo '#!/bin/bash' > /tmp/join-command.txt
        kubeadm token create --kubeconfig="/home/{{ username }}/.kube/config" \
          --print-join-command >> /tmp/join-command.txt

    - name: Copy join command to local file
      fetch:
        src: /tmp/join-command.txt
        dest: "{{ continuum_home }}/"
        flat: true

    - name: Remove unneeded Kubernetes join command file
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/join-command.txt
