---
- hosts: base_cloud
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common

    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Add cloud user to docker group
      user:
        name: "{{ username }}"
        groups: docker
        append: true

    - name: Allow HTTP pulling from private docker registry
      shell: echo '{ "insecure-registries":["{{ registry_ip }}"] }' > /etc/docker/daemon.json

    - name: Restart docker service
      command: systemctl restart docker

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Make sure swap is disabled even after reboot
      command: sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Enable ipv4 forwarding
      shell: echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf

    - name: Reload ip settings
      command: sysctl -p

    - name: Create keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add an apt signing key for Kubernetes - no need to ever change the version number here
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Adding apt repository for Kubernetes - change version number if needed
      apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl

    - name: Get Flannel
      get_url:
        url: https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
        dest: /
        mode: "0755"

    - name: Install Mosquitto
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: true
      vars:
        packages:
          - mosquitto=1.6.9-1

    - name: Update SSH settings to allow many parallel sessions
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          MaxSessions 10000
          MaxStartups 10000

    - name: Clone kube-prometheus
      command: git clone https://github.com/prometheus-operator/kube-prometheus.git /kube-prometheus

    - name: Git checkout
      command: git checkout release-0.9
      args:
        chdir: /kube-prometheus

    - name: Reset SSH client
      command: systemctl restart sshd
