---
- hosts: edges
  become: true
  tasks:
  - name: Create edge images
    shell: |
      for i in $(seq "{{ edge_start }}" "{{ edge_end }}"); do
        qemu-img create -f qcow2 -F qcow2 -b "/var/lib/libvirt/images/{{ base }}.qcow2" /var/lib/libvirt/images/edge${i}.qcow2
      done

  - name: Add cloudinit disk
    shell: |
      for i in $(seq "{{ edge_start }}" "{{ edge_end }}"); do
        cloud-localds /var/lib/libvirt/images/user_data_edge${i}.img "/home/{{ username }}/.continuum/user_data_edge${i}.yml"
      done
