---
- hosts: cloudcontroller
  become: true
  tasks:
    - name: Create OpenFaaS deployment file
      shell: |
        cat > "/home/{{ username }}/function.yml" <<EOF
        provider:
          name: openfaas
          gateway: http://127.0.0.1:8080

        functions:
          {{ app_name }}:
            image: {{ image }}
            environment:
              CPU_THREADS: "{{ cpu_threads }}"
            requests:
              memory: "{{ memory_req }}Mi"
              cpu: {{ cpu_req }}
        EOF

    - name: Forward incoming 8080 traffic to localhost
      command: iptables -t nat -A PREROUTING -i ens2 -p tcp --dport 1883 -j REDIRECT --to-port 8080

    - name: Launch jobs
      command: faas-cli deploy --yaml "/home/{{ username }}/function.yml"
